channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1
- pip:
  - mlflow==3.1.1
  - bottleneck==1.4.2
  - cffi==1.17.1
  - cloudpickle==3.0.0
  - colorama==0.4.6
  - cytoolz==1.0.1
  - defusedxml==0.7.1
  - distributed==2025.2.0
  - lightgbm==4.6.0
  - lz4==4.3.2
  - matplotlib==3.10.0
  - numpy==2.1.3
  - pandas==2.2.3
  - pyarrow==19.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xarray==2025.4.0
  - zstandard==0.23.0
name: mlflow-env
